Importing the Data

In [1]:
import pandas as pd

In [2]:
url = 'https://raw.githubusercontent.com/QhungChang/POLI3148-Assignment-1/refs/heads/main/number_of_demonstration_events_by_country-year_as-of-03Apr2026.csv'

In [7]:
url2 = 'https://raw.githubusercontent.com/QhungChang/POLI3148-Assignment-1/refs/heads/main/data/US-and-Canada_aggregated_data_up_to_week_of-2026-03-28.csv'

In [8]:
url3 = 'https://raw.githubusercontent.com/QhungChang/POLI3148-Assignment-1/refs/heads/main/data/Middle-East_aggregated_data_up_to_week_of-2026-03-21.csv'

In [9]:
url4 = 'https://raw.githubusercontent.com/QhungChang/POLI3148-Assignment-1/refs/heads/main/data/Latin-America-the-Caribbean_aggregated_data_up_to_week_of-2026-03-21.csv'

In [10]:
url5 = 'https://raw.githubusercontent.com/QhungChang/POLI3148-Assignment-1/refs/heads/main/data/Europe-Central-Asia_aggregated_data_up_to_week_of-2026-03-28.csv'

In [11]:
url6 = 'https://raw.githubusercontent.com/QhungChang/POLI3148-Assignment-1/refs/heads/main/data/Asia-Pacific_aggregated_data_up_to_week_of-2026-03-28.csv'

In [12]:
url7 = 'https://raw.githubusercontent.com/QhungChang/POLI3148-Assignment-1/refs/heads/main/data/Asia-Pacific_aggregated_data_up_to_week_of-2026-03-28%20(2).csv'

In [13]:
url8 = 'https://raw.githubusercontent.com/QhungChang/POLI3148-Assignment-1/refs/heads/main/data/Africa_aggregated_data_up_to_week_of-2026-03-21.csv'

In [14]:
url9 = 'https://raw.githubusercontent.com/QhungChang/POLI3148-Assignment-1/refs/heads/main/data/Africa_aggregated_data_up_to_week_of-2026-03-21%20(2).csv'

In [22]:
demo = pd.read_csv(url)
North_America = pd.read_csv(url2)
Middle_East = pd.read_csv(url3)
Latin_America = pd.read_csv(url4)
Europe_Central_Asia = pd.read_csv(url5)
Asia_Pacific = pd.read_csv(url6)
Asia_Pacific2 = pd.read_csv(url7)
Africa = pd.read_csv(url8)
Africa2 = pd.read_csv(url9)

Merging the Data

In [23]:
all = pd.concat([
    North_America,
    Middle_East,
    Latin_America,
    Europe_Central_Asia,
    Asia_Pacific,
    Asia_Pacific2,
    Africa,
    Africa2
], ignore_index=True)

Checking the Data

In [24]:
demo.head()

       COUNTRY  YEAR  EVENTS
0  Afghanistan  2017     135
1  Afghanistan  2018     225
2  Afghanistan  2019      61
3  Afghanistan  2020     147
4  Afghanistan  2021     234

In [25]:
all.head()

,WEEK,REGION,COUNTRY,ADMIN1,EVENT_TYPE,SUB_EVENT_TYPE,EVENTS,FATALITIES,POPULATION_EXPOSURE,DISORDER_TYPE,ID,CENTROID_LATITUDE,CENTROID_LONGITUDE
0,09-April-2022,North America,Bermuda,Devonshire,Protests,Peaceful protest,1,0,1882.0,Demonstrations,3888.0,32.3033,-64.7595
1,01-May-2021,North America,Bermuda,Pembroke,Protests,Peaceful protest,1,0,2260.0,Demonstrations,3891.0,32.2991,-64.7896
2,26-June-2021,North America,Bermuda,Pembroke,Protests,Peaceful protest,1,0,2260.0,Demonstrations,3891.0,32.2991,-64.7896
3,28-August-2021,North America,Bermuda,Pembroke,Protests,Peaceful protest,2,0,2260.0,Demonstrations,3891.0,32.2991,-64.7896
4,06-November-2021,North America,Bermuda,Pembroke,Protests,Peaceful protest,1,0,2260.0,Demonstrations,3891.0,32.2991,-64.7896

Check for Missing Values

In [26]:
all[pd.isnull(all.REGION)]

#No missing values

Empty DataFrame
Columns: [WEEK, REGION, COUNTRY, ADMIN1, EVENT_TYPE, SUB_EVENT_TYPE, EVENTS, FATALITIES, POPULATION_EXPOSURE, DISORDER_TYPE, ID, CENTROID_LATITUDE, CENTROID_LONGITUDE]
Index: []